In [1]:
import numpy as np

In [2]:
def get_spin(state,site):
    return (state>>site)&1

In [3]:
def flip_spin(state,site):
    return state^(1<<site)

In [4]:
def make_ham(L,g):
    Nstate = 2**L
    Ham = np.zeros((Nstate,Nstate),dtype=np.float64)
    for a in range(Nstate):
        for i in range(L):
            if get_spin(a,i) == get_spin(a,(i+1)%L):
                Ham[a,a] -= 1.0
            else:
                Ham[a,a] += 1.0
        for i in range(L):
            b = flip_spin(a,i)
            Ham[a,b] -= g
    return Ham

In [5]:
def main():
    L = 2; g = 1.0
    Ham = make_ham(L,g)
    print("Hamiltonian:\n",Ham)
    Ene, Vec = np.linalg.eigh(Ham)
    print("Ground state energy:\n",Ene[0])
    print("Ground state vector:\n",Vec[:,0])

In [6]:
main()

Hamiltonian:
 [[-2. -1. -1.  0.]
 [-1.  2.  0. -1.]
 [-1.  0.  2. -1.]
 [ 0. -1. -1. -2.]]
Ground state energy:
 -2.82842712474619
Ground state vector:
 [-0.65328148 -0.27059805 -0.27059805 -0.65328148]
